config/routes.rb
Rails.application.routes.draw do
  # get 'users/new'
  resources :users
  resources :lists do
    resources :tasks do
      collection { post :sort}
    end
  end
  root 'lists#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	belongs_to :user
	validates :user_id, presence: true

	has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  acts_as_list :column => :order
  # before_create :set_order
  default_scope -> {order(:done).order(:order)}

  def deadline_info
    # return "fff"
    return '' unless deadline.present?
    case 
      when deadline < DateTime.current 
        'danger'
      when deadline < DateTime.current + 2.days
        'warning'
      when deadline > DateTime.current + 2.days && deadline < DateTime.current + 5.days
        'attention'
      when deadline > DateTime.current + 5.days
        'normal'
    end
  end

  private

  # def set_order
  #   if self.list.tasks.size == 0
  #     self.order = 1
  #   else
  #     self.order = list.tasks.last.order + 1
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
																		format: { with: VALID_EMAIL_REGEX },
								                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :verify_authenticity_token

  expose :lists, -> { List.all }
  expose :list

  def new
    @list = List.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @list = current_user.lists.create(list_params)
    # @task = list.tasks.create!(task_params)
    p @list.id 
    respond_to do |format|
      format.js
    end
  end

  def show
  end

  def edit
  end

  def update
    list.update(list_params)
  end

  def destroy
    list.destroy

  end

  def index
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      # flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :verify_authenticity_token

  expose :task
  expose :list 
  

  def new

  end

  def create
    @task = list.tasks.create!(task_params)
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    task.update(task_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    task.destroy
    respond_to do |format|
      format.js
    end
  end

  def sort
    params[:task].each_with_index do |id, index|
      Task.find(id).update(order: index+1)
    end
  end

  def index
  end

  private

  def task_params
    params.require(:task).permit(:done, :name, :list_id, :deadline)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # expose :user
  # expose :lists, -> { user.lists}
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

 	def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<header class="header">
  <nav class="navbar", style="display: flex; justify-content: space-between;">
    <div class="navbar-left">
      <%= link_to "<i class='fal fa-home'></i>".html_safe , root_path, class: "link" %>
    </div>
    <div class="navbar-right">
      <% if logged_in? %>
        <%= link_to "<i class='fal fa-sign-out-alt'></i>".html_safe, logout_path, class: "link", method: :delete %>
      <% else %>
        <%= link_to "Sign Up", new_user_path, class: "link" %>
        <%= link_to "Sign In", login_path, class: "link" %>
      <% end %>
    </div>
  </nav>
</header>

app/views/application/_messages.html.erb
<% flash.each do |type, content| %>
  <div class="callout <%= type %>">
    <%= content %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="/fontawesome/css/all.css">
  </head>

  <body>
    <%= render "header" %>
    <%= render "messages" %>
    
    <%= yield %>
  </body>
</html>

app/views/lists/_edit.html.erb
<!-- <div class="list_update"> -->
<%= simple_form_for [list], action: :update, remote: true do |f|%>

<%#= f.label :name %>
<%= f.text_field :name %>

<%= f.submit "update todo list", class: "edit_list-btn" %>
<% end %>
<!-- </div> -->

app/views/lists/_index.html.erb
	<div class="lists container">
		<%= render current_user.lists %>
	</div>
	<div class="add_list">
		<div class="container ">
			<div class="add_list-btn">
			
			<%= link_to  new_list_path, class: "add_list-text", remote: true do %>
				<i class='fas fa-plus add_list-icon'></i>
				<p>Add TODO List</p>
			<% end %>
			</div>
		</div>
	</div>

app/views/lists/_list.html.erb
<div id="list_<%=list.id%>" class="todo_list" style="margin: 10px" >
	<%# @list = list %>
	<%# p list.id  %>
	<%= render 'lists/list_info', list: list %>
	<%= render partial:'tasks/new', locals:{list: list}  %>
</div>

<script type="text/javascript">
	$(function () {
	$("#list_<%=list.id%> .title").after("<%= j render 'tasks/form', list: list %>");
  $("#list_<%= list.id %> .new_task #new_task").find('#task_deadline').datetimepicker({ format: 'd.m.Y H:i' });
	});
</script>

app/views/lists/_list_info.html.erb
<div class="title">
	<i class="fas fa-calendar-alt title-icon"></i>
	<h2 class="title-text"> 
    <%= list.name %>
  </h2>
	<%= link_to  edit_list_path(id: list.id), class: "title-edit", remote: true do %>
		<i class="fas fa-pen "></i>
	<% end %>
	<%= link_to  list_path(id: list.id), class: "title-delete", method: :delete, remote: true do %>
		<i class="fas fa-trash-alt "></i>
	<% end %>
</div>

app/views/lists/_new.html.erb
<div class="x">x</div>
	<%= simple_form_for @list, class: "add_list-form", action: :new, remote: true do |f| %>
	
	<%= f.label "List Name"%>
	
	<%= f.text_field :name %>

	<%= f.submit "Create todo list", class: 'new_list-btn'%>
	<% end %>

app/views/lists/create.js.erb
$(".page .lists").remove();
$(".add_list").remove();
$("#new_list").remove();
$(".x").remove();
$(".page ")
			.append("<%= j render partial:'lists/index', locals:{list: @lists}%>");

app/views/lists/destroy.js.erb
$("#list_<%= list.id %>").remove();

app/views/lists/edit.html.erb
<div>
<%= form_for(@list) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit "update todo list"%>
<% end %>
</div>

app/views/lists/edit.js.erb
$("#list_<%= list.id %> .tasks").remove();
// $("#list_<%#= @list.id %> .new_task").remove();
$("#list_<%= list.id %>")
			.append("<%= j render partial:'tasks/new' %>");
$("#list_<%= list.id%> .title-text").remove();
$("#list_<%= list.id%> .title-edit").remove();
$("#list_<%= list.id%> .title-delete").remove();
$("#list_<%= list.id%> .title")
			.append("<%= j render partial:'lists/edit'%>");

app/views/lists/index.html.erb
<div class="page">
  	<% if logged_in? %> 
      <%= render partial:'lists/index'%>
    <% else %>
      <div class="welcome container">
        Hello, you must either
        <%= link_to "register", new_user_path, class: "links"%>
        or
        <%= link_to "login", login_path, class: "links"%>
        to create a new todo list.
      </div>
    <% end %>
</div>

app/views/lists/new.html.erb
<% provide(:title, 'New todo')%>
<h1>New todo</h1>
<div class="row">
<%= form_for(@list) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit "Create todo list"%>
<% end %>
</div>

app/views/lists/new.js.erb
$("body").css( 'overflow', 'hidden' )
$(".page").append("<%= j render partial:'lists/new', locals:{list: @list} %>");
$(".x").click( function() {
	$("#new_list").remove();
	$(".x").remove();
	$("body").css( 'overflow', '' )
});

app/views/lists/show.html.erb
<h1>dd</h1>
<div>
	<%= @list.name %>
	<br>
	<%#= link_to 'edit', edit_list_path(@list) %>
	<%#= link_to 'delete', @list, method: :delete %>
	<%= link_to 'new task', new_list_task_path(@list) %>
	<%= render @tasks %>
	<div>
		<%= link_to 'back to lists', lists_path %>
	</div>
</div>

app/views/lists/update.js.erb
$("#list_<%= list.id%> .title").remove();
$("#list_<%= list.id%> ")
			.prepend("<%= j render partial:'lists/list_info'%>");

app/views/tasks/_edit.html.erb
<!-- <div class="task_edit"> -->
	<%= simple_form_for [task.list, task], action: :update, remote: true do |f| %>
	<%= f.hidden_field :list_id, value: task.list.id %>
	<%= f.text_field :name %>
	<div class="deadline">
		<%= f.input :deadline, value: task.deadline, as: :string, label: false, input_html: { placeholder: "Deadline", autocomplete: "off" } %>
	</div>
	<%= f.submit "update task", class: "update"%>
	<% end %>

<!-- </div> -->

app/views/tasks/_form.html.erb
<div class="new_task">
	<i class='fas fa-plus new_task-add'></i>
	<%# p list.id  %>
	<%#= simple_form_for [@task.list, @task], action: :new, remote: true do |f| %>
	<%= simple_form_for [list, list.tasks.build], html: { class: "new_task-form"}, action: :new, remote: true do |f| %>
	<%#= form_with url: list_tasks_path(task.list, task), model: task, method: :post do |f| %>
		<%= f.hidden_field :token, value: list.id %>
		<%#= @task.list_id%>
		<%= f.hidden_field :list_id, value: list.id %>

		<%#= f.label :name %>
		<%= f.text_field :name, class: "new_task-input", placeholder: "Start typing here to create a task" %>
		<%= f.input :deadline, as: :string, label: false, input_html: {class: "new_task-deadline", placeholder: "Deadline", autocomplete: "off" } %>

		<%= f.submit "Create task", class: "new_task-btn" %>
	<% end %>
</div>

app/views/tasks/_info.html.erb
	<div class="tasks_item-checkbox">
		<%# p task.id %>
		<%= check_box_tag "name", [task.list.id, task.id], task.done, :class => "tasks_item-check" %>
	</div>
	<div class="tasks_item-text <%= task.deadline_info %>">
		<div class="task ">
			<%= task.name %> 
		</div>
		<div class="deadline ">
		<% if task.deadline.present? %>
    	<%= "#{task.deadline.strftime("%d.%m.%Y %H:%M")}" %>
     <% end %>
 		</div>
	</div>
  <div class="tasks_item-modify">
  	<i class="fas fa-arrows-alt-v drag handle"></i>
  	<div class="task_item-edit">
			<%= link_to edit_list_task_path(task.list, task), remote: true do %>
				<i class="fas fa-pen"></i>
			<% end %>
		</div>
		<div class="task_item-delete">
			<%= link_to list_task_path(task.list, task), method: :delete, remote: true do %>
				<i class="fas fa-trash-alt"></i>
			<% end %>
		</div>
	</div>

app/views/tasks/_new.html.erb
<!-- <div class="new_task">
	<%#= link_to "New task", new_list_task_path(@list), remote: true %>
</div> -->
<%# p @list %>
<%#= render partial:'tasks/form', locals:{list: @list} %>
<div class="tasks" data-update-url="<%= sort_list_tasks_path(list_id: list.id) %>" >
	<%# p list.tasks %>
	<%= render list.tasks %>
</div> 

app/views/tasks/_task.html.erb
<li class="tasks_item" id="task_<%=task.id%>">
	<%# p task.id %>
	<div class="tasks_item-checkbox">
		<%# p task.id %>
		<%= check_box_tag "name", [task.list.id, task.id], task.done, :class => "tasks_item-check" %>
	</div>
	<div class="tasks_item-text <%= task.deadline_info %>">
		<div class="task ">
			<%= task.name %> 
		</div>
		<div class="deadline ">
		<% if task.deadline.present? %>
    	<%= "#{task.deadline.strftime("%d.%m.%Y %H:%M")}" %>
     <% end %>
 		</div>
	</div>
  <div class="tasks_item-modify">
  	<i class="fas fa-arrows-alt-v drag handle"></i>
  	<div class="task_item-edit">
			<%= link_to edit_list_task_path(task.list, task), remote: true do %>
				<i class="fas fa-pen"></i>
			<% end %>
		</div>
		<div class="task_item-delete">
			<%= link_to list_task_path(task.list, task), method: :delete, remote: true do %>
				<i class="fas fa-trash-alt"></i>
			<% end %>
		</div>
	</div>
	<%#= render 'tasks/info', task: task  %>
</li>

app/views/tasks/create.js.erb
$("#list_<%= list.id %> .tasks").remove();
$("#list_<%= list.id %> .new_task").remove();
$("#list_<%= list.id %> ")
			.append("<%= j render partial:'tasks/new' %>");
$("#list_<%=list.id%> .title")
			.after("<%= j render 'tasks/form', list: list %>");

app/views/tasks/destroy.js.erb
$("#list_<%= list.id %> .tasks").remove();
$("#list_<%= list.id %> ")
			.append("<%= j render 'tasks/new', list: list %>");
			// .append("<%#= j render partial:'tasks/info', locals:{task: @task} %>");

app/views/tasks/edit.html.erb
<h1><%= edit_list_task_path(@task.list, @task) %></h1>
<div>
	<%= form_with model: [:list, @task] do |f| %>
	<%= f.hidden_field :list_id, value: @task.list.id %>
	<%= f.check_box :done %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit "update task"%>
	<% end %>

</div>

app/views/tasks/edit.js.erb
$("#list_<%= list.id %> .tasks").remove();
$("#list_<%= list.id %>")
			.append("<%= j render partial:'tasks/new' %>");
$("#task_<%= task.id%> .tasks_item-checkbox").remove();
$("#task_<%= task.id%> .tasks_item-text").remove();
$("#task_<%= task.id%> .tasks_item-modify").remove();
$("#task_<%= task.id %> ")
			.append("<%= j render partial:'tasks/edit', locals:{task: task} %>");
$(function () {
	console.log("<%= task.id %>")
  $("#edit_task_<%= task.id %> ").find('#task_deadline').datetimepicker({ format: 'd.m.Y H:i' });
  $("#edit_task_<%= task.id %> ").find('#task_name').focus();
});

app/views/tasks/update.js.erb
$("#list_<%= list.id %> .tasks").remove();
$("#list_<%= list.id %>")
			.append("<%= j render 'tasks/new', list: list %>");

app/views/users/new.html.erb
<div class="new_user-form">
  <h1>Sign up</h1>
  <%= simple_form_for @user, action: :new, remote: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name,  class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Create my account", class: "new_user-btn" %>
  <% end %>
</div>